### ISSUE TITLE
Will the development process of predictive models be included in the future?

### ISSUE THREAD

**Issue by JinChengneng** [MolecularAI/ReinventCommunity#1]
Hi there, thanks for your efforts to Reinvent and its community. However, I've found that the codes of how to build a predictive model such as ```drd2``` or ```Aurora_model```, which are essential to the training process, are not included in this repository. I would appreciate it if you could provide a demo for the development of the predictive models.

**Comment by CMargreitter** [comment]
Thanks for your interest!

True, as of yet we don't provide a tutorial of how to train a QSAR model for `REINVENT` with `scikit-learn`.
We will add that asap.

**Comment by JinChengneng** [comment]
I've checked the latest commit and it's exactly what I want. Thanks a lot!

**Comment by CMargreitter** [comment]
Great! Note, that you will need to update the environment from "environment.yml" as an additional dependency is required now. The descriptor definition in your `REINVENT` JSON will have to match the descriptors used for model training.
