### ISSUE TITLE
Saving trained model

### ISSUE THREAD

**Issue by MiloszGrabski** [MolecularAI/ReinventCommunity#12]
Hi,
How do I recover trained model (I assume from results/Agent.ckpt) and use it to generate compounds without retraining?
Kind regards,
M

**Comment by CMargreitter** [comment]
Hi Milosz,

If I understand your question correctly, you should have a look at the [Sampling Notebook](https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Sampling_Demo.ipynb). It explains how to sample further compounds from a given model state (agent).

Best,
Christian

**Comment by MiloszGrabski** [comment]
Hi Christian,
Thank you, this is exactly what I was looking for.
Kinds regards,
Milosz
