### ISSUE TITLE
reinforcement learning notebook does not work

### ISSUE THREAD

**Issue by dd1github** [MolecularAI/ReinventCommunity#15]
Hi, the reinforcement learning notebook does not work.  It returns an error saying that aurora is not a valid scikit learn model, just like the base case says that drd2 is not a valid scikit learn file.

**Comment by GemaRG96** [comment]
Hi! I'm facing the same problem. I just installed today both Reinvent.v3.2 and ReinventCommunity. Any advice on what to do?

**Comment by ggokturkk** [comment]
![Ekran Resmi 2022-11-16 13 32 31](https://user-images.githubusercontent.com/97913215/202157232-bacf87aa-979b-4501-9237-86732687f1f9.png)

I think it's not fixed. I used both aurora_model files in the models directory but, it gave me this error. 
@GuoJeff

**Comment by MKCarter** [comment]
Hey,

Just to let you know, the models are still corrupted, even in the latest versions. Using the DRD2 model generated from the notebooks does work. 

Thanks,
Mike
