### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by yipy0005** [MolecularAI/ReinventCommunity#20]
I tried running of the notebooks (REINVENT_Use-Case-DRD2_demo). When I was trying to execute python input.py DRD2_config.json, it gave the error: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

What could have gone wrong? The generated json file is okay when I tried to read its contents with:

with open(file_path, 'r') as j:
     contents = json.loads(j.read())
     print(contents)

**Comment by patronov** [comment]
To me it still appears like an issue with the JSON. Would you be able to share it here?
