### ISSUE TITLE
Notebook illustrating DockStream integration

### ISSUE THREAD

**Issue by CMargreitter** [MolecularAI/ReinventCommunity#21]
While all the details are described in the DockStreamCommunity repository, we should have a (simple) notebook here illustrating how to set up a ADV docking component.

**Comment by GuoJeff** [comment]
A tutorial notebook demonstrating the use of DockStream in REINVENT is now available at https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Reinforcement_Learning_Demo_DockStream.ipynb
