### ISSUE TITLE
Hard time getting into the tutorials

### ISSUE THREAD

**Issue by WoutVanEynde** [MolecularAI/ReinventCommunity#27]
As of now I am following DRD2 use-case but I am stuck at the line:

"Before we start diving into this, though execute the following code blocks to set the configurations as required."

I had to open the jupyter notebook previously, but I do not know what to do next. Do I just upload the "Complete_Use-Case-DRD2_Demo.ipynb" file and work from here? Or do I upload it in the C/GBW_MyPrograms/Anacondalinux/envs/ReinventCommunity directory?

Keep in mind that I have **no** experience whatsoever with programming.

EDIT: I just uploaded into the C drive, and continued forward, however I stumble at this block of code:

_#### write the configuration file to the disc
configuration_JSON_path = os.path.join(output_dir, "DRD2_config.json")
with open(configuration_JSON_path, 'w') as f:
    json.dump(configuration, f, indent=4, sort_keys=True)_
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-16-07fb8c31a989> in <module>
      1 #### write the configuration file to the disc
      2 configuration_JSON_path = os.path.join(output_dir, "DRD2_config.json")
----> 3 with open(configuration_JSON_path, 'w') as f:
      4     json.dump(configuration, f, indent=4, sort_keys=True)

FileNotFoundError: [Errno 2] No such file or directory: '/home/woutvaneynde/woutvaneynde/c/GBW_MyPrograms/REINVENT/Complete_Use-Case-DRD2_Demo/DRD2_config.json'

I should have the file and directory, however it tells me I do not.

Warm regards,
Wout Van Eynde, master chemistry at the KU Leuven

**Comment by GuoJeff** [comment]
Hi @WoutVanEynde,

You do not have to upload any files to run the notebook. If you clone the repository using this command in your terminal:
`git clone https://github.com/MolecularAI/ReinventCommunity.git`, the ReinventCommunity repository will be downloaded onto your computer. 

Next, you can create the conda environment using the environment.yml file provided in the repository with the following command:
`conda env create -f environment.yml`

Once the conda environment is installed, you can activate it with the following command:
`conda activate ReinventCommunity`

If you now use the command:
`jupyter notebook`

A jupyter notebook instance will launch in your web browser. There, you can open the "Complete_Use-Case-DRD2_Demo.ipynb" notebook. The only paths you need to change in the notebook are in the first cell block:

`reinvent_dir = os.path.expanduser("~/Desktop/Reinvent")`
`reinvent_env = os.path.expanduser("~/miniconda3/envs/reinvent.v3.2")`
`output_dir = os.path.expanduser("~/Desktop/REINVENT_Use-Case-DRD2_demo")`

You need to clone the Reinvent repository at: https://github.com/MolecularAI/Reinvent using the following command in your terminal: `git clone https://github.com/MolecularAI/Reinvent.git`

the `reinvent_dir` path should then be changed to where you installed the `Reinvent` repository. The `reinvent_env` is the location of the installed conda environment for `Reinvent`. To install that conda environment, change your directory to the now installed `Reinvent` folder and the steps are the same as above using the  `conda env create -f environment.yml` command. The last thing to change is `output_dir`. This specifies the path where you want to save all the files generated in the notebook, including results files. After changing these paths, the notebook should run as is.

**Comment by WoutVanEynde** [comment]
This all worked, but I still got the error message at the following blocks:

# load dependencies
import os
import re
import json
import tempfile

# --------- change these path variables as required
reinvent_dir = os.path.expanduser("C/GBW_MyPrograms/Reinvent")
reinvent_env = os.path.expanduser("C/GBW_MyPrograms/Anacondalinux/envs/reinvent.v3.2")
output_dir = os.path.expanduser("C/GBW_MyPrograms/ReinventCommunity/Complete_Use-Case-DRD2_Demo")

# --------- do not change
# get the notebook's root path
try: ipynb_path
except NameError: ipynb_path = os.getcwd()

# if required, generate a folder to store the results
try:
    os.mkdir(output_dir)
except FileExistsError:
    pass
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-38-4369499d0155> in <module>
     17 # if required, generate a folder to store the results
     18 try:
---> 19     os.mkdir(output_dir)
     20 except FileExistsError:
     21     pass

FileNotFoundError: [Errno 2] No such file or directory: 'C/GBW_MyPrograms/ReinventCommunity/notebooks/Complete_Use-Case-DRD2_Demo'





# write the configuration file to the disc
configuration_JSON_path = os.path.join(output_dir, "DRD2_config.json")
with open(configuration_JSON_path, 'w') as outfile:
    json.dump(configuration, f, indent=4, sort_keys=True)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-5231c98de660> in <module>
      3 
      4 configuration_JSON_path = os.path.join(output_dir, "DRD2_config.json")
----> 5 with open(configuration_JSON_path, 'w') as outfile:
      6     json.dump(configuration, f, indent=4, sort_keys=True)

FileNotFoundError: [Errno 2] No such file or directory: 'C/GBW_MyPrograms/ReinventCommunity/notebooks/Complete_Use-Case-DRD2_Demo/DRD2_config.json'

I do not really get why it is looking for a file that has to be written?

Warm regards,
Wout Van Eynde

**Comment by WoutVanEynde** [comment]
Problem solved! It seems when placing my output_dir in the GBW_MyPrograms directory, I would always get this error! This folder is special for work, so that might be the cause!

Thanks for helping me anyway!
