### ISSUE TITLE
Data Preparation demo question

### ISSUE THREAD

**Issue by recherHE** [MolecularAI/ReinventCommunity#3]
When I try to use this demo to perpare individual database,there was some error as follow:
NameError: name 'SparkSessionSingleton' is not defined

and I have no clue to find this function,could you help me out? thanks a lot!

**Comment by patronov** [comment]
If this is about the Data_Preparation notebook it seems to me that you havent executed the third cell which is responsible for importing the "**SparkSessionSingleton**" class:

Below is the cell's core: 

%matplotlib inline
import pyspark.sql as ps
import pyspark.sql.functions as psf
import pyspark.sql.types as pst

import rdkit.Chem as rkc
import rdkit.Chem.AllChem as rkac

import molvs as mv

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

%run code/data_preparation.py
