### ISSUE TITLE
Constraint on key interactions while integrating DockStream with Re-INVENT

### ISSUE THREAD

**Issue by shkao** [MolecularAI/ReinventCommunity#32]
Hi,

First of all, thank you for the great work of developing and releasing these invaluable resources!
I recently integrated the docking score as a reward/score component using DockStream (AutoDock Vina).
I wonder, would it be possible to set a constraint on key interactions during docking, in other words, can I provide my own pharmacophore hypothesis as a setting for filtering?
Or, filtering on critical protein residues with certain interactions after analyzing using [PLIP](https://plip-tool.biotec.tu-dresden.de/plip-web/plip/index).
Is there any similar functionality already?

**Comment by GuoJeff** [comment]
Hi @shkao,

Sorry for the delayed response. The implemented version of AutoDock Vina in DockStream does not support any docking constraints (I believe a newer version of AutoDock Vina does). By contrast, Glide supports constrained docking and you can enforce hydrogen bond interactions to be retained. The result is REINVENT learns to propose compounds which satisfy your desired docking constraint. Using Glide however requires a Schrodinger license as it is a proprietary software.

**Comment by shkao** [comment]
I see, thank you, @GuoJeff !
