### ISSUE TITLE
what data used for prior

### ISSUE THREAD

**Issue by rneeser** [MolecularAI/ReinventCommunity#35]
Hi!
Thanks for this awesome collection!
I was wondering what dataset exactly was used to train the model `random.prior.new`. I assume this is the version using data from ChEMBL with randomized SMILES? What additional filters where there applied in terms of:
- element types
- number of heavy atoms
- max number of e.g. rings with or without heteroatoms
- deduplication based on stereochemistry

Thanks!

**Comment by halx** [comment]
Sorry for the late reply.  I would need to refer you to the relevant papers where details of prior preparation have been discussed in some detail.
