### ISSUE TITLE
Tutorial for Transfer Learning of Link-INVENT

### ISSUE THREAD

**Issue by ismorphism** [MolecularAI/ReinventCommunity#37]
Hello, Reinvent team! REINVENT is an amazing tool and it really helps with idea generation, but going through the notebooks I've found that it's not really clear how to use Transfer Learning idea for Link-INVENT. Is there any Jupyter notebook about this? Existing scripts/notebooks cover Transfer Learning for default REINVENT and do not work for Link-INVENT. There are files:

- `link_invent_transfer_learning_configuration.py`
- `link_invent_learning_rate_configuration.py`
- `link_invent_transfer_learning_runner.py`

but going through them without proper documentation it's not an easy way for novices. It would be great to see some additional notebook about this topic :heart:

**Comment by halx** [comment]
Many thanks for this.  We will see if we can include your suggestions in the new release.

**Comment by ismorphism** [comment]
> Many thanks for this. We will see if we can include your suggestions in the new release.

Thanks for the answer!

**Comment by halx** [comment]
Thinking about it, I wonder how useful TL would with together with LinkInvent..  The idea of the TL implementation is to bias a model towards a set of input structures.  That's how our priors have been trained and this also makes sense with classical Reinvent when you are trying to limit molecular structure.  With LinkInvent you however already have a constraint for the linkers.  So it would seem more useful to me to run RL with a suitable objective.  I am happy to hear though about use cases for LinkInvent/TL.
