### ISSUE TITLE
Outdated instructions?

### ISSUE THREAD

**Issue by yoctocell** [MolecularAI/ReinventCommunity#5]
The `Complete_Use-Case-DRD2_Demo.ipynb` file, it tells me to run
`conda env create -f reinvent_shared.yml`, but there is no
`reinvent_shared.yml` file, only an `environment.yml` file.  However,
when passing `environment.yml`, conda fails to create the environment.

```
~/src/ReinventCommunity $ conda env create -f environment.yml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - ld_impl_linux-64==2.34=h53a641e_0
```

**Comment by patronov** [comment]
Thanks for spotting this. I guess we updated the environment without reflecting the notebooks. Note that the name of the resulting environment from the current "_environment.yml_" will be "_ReinventCommunity_". 
The problem you are encountering can be fixed by removing "ld_impl_linux-64=2.34=h53a641e_0" from the "_environment.yml_"  file. Let me know if the problem still persists I will update the *.yml

**Comment by CMargreitter** [comment]
Do you have a .bashrc file? There was a bug once that made conda believe it requires sudo access to activate the environment if this file was missing (AFAIR).

**Comment by yoctocell** [comment]
> Do you have a .bashrc file? There was a bug once that made conda believe it requires sudo access to activate the environment if this file was missing (AFAIR).

Yeah, below is the content of it (if you're curious).

```
# -*- mode: sh -*-



# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return

HISTCONTROL=erasedups
HISTFILE="/home/yoctocell/.config/bash/history"
HISTFILESIZE=100000
HISTIGNORE=cd:pwd
HISTSIZE=10000

shopt -s histappend
shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s checkjobs

GPG_TTY="$(tty)"
export GPG_TTY

export PS1="\n\w $ "
# Only show 3 deepest directories
# <https://askubuntu.com/questions/145618/how-can-i-shorten-my-command-line-bash-prompt>
PROMPT_DIRTRIM=3

eval "$(/nix/store/h57n91xvgv3901v990zxiy96djwhl1zn-direnv-2.28.0/bin/direnv hook bash)"
```

**Comment by CMargreitter** [comment]
Two more suggestions:

Try "conda init" (without the bash, let it figure it out by itself). If that doesn't work, try "activate ReinventCommunity" (without the "conda").

**Comment by yoctocell** [comment]
Running `conda init` results in the same error as above.  Just running
`activate ReinventCommunity` doesn't output anything (which is usually
a good thing on Unix).  But trying to import a library from the REPL
doesn't seem to work.

```
~/src/ReinventCommunity $ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

**Comment by patronov** [comment]
Did you try closing and opening the console?

Is the python command executed under a given conda environment?
If you are under a conda environment the console should be showing something like: 
`(ReinventCommunity) [your_username]$`

Another possibility is that there is some issue with the installation.
Are you able to create/start other environments?
Here is a useful [link](https://docs.conda.io/projects/conda/en/4.6.1/user-guide/tasks/manage-environments.html)

**Comment by yoctocell** [comment]
> Did you try closing and opening the console?

When exactly should I do that?  I tried this multiple times and the
result seems to be the same.

> Is the python command executed under a given conda environment?

Presumably not; it's not able to import the Python libraries so I guess
something is broken with conda.

> If you are under a conda environment the console should be showing
> something like: (ReinventCommunity) [your_username]$

My `PS1` didn't change so the environment was probably not active,
even though I ran `activate ReinventCommunity`.

> Another possibility is that there is some issue with the installation.

Yeah, that could be the case.

> Are you able to create/start other environments?

I haven't tried it on other environments yet.

> Here is a useful link

Thanks for the link, I will look into it.

**Comment by yoctocell** [comment]
Something else I noted, it is unclear to me what the `reinvent_dir`
variable in the example notebooks refer to.  Is it the path to my
local checkout of the Reinvent Git repository?

**Comment by patronov** [comment]
Yes, correct `reinvent_dir ` should be pointing where you have cloned the Reinvent code.
