### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by Shiska07** [MolecularAI/ReinventCommunity#6]
I tried to create the environment using
conda env create -f environment.yml

and kept getting this error:
ResolvePackageNotFound:
  - boost-cpp==1.72.0=h8e57a91_0
  - zlib==1.2.11=h516909a_1006
  - gstreamer==1.14.5=h36ae1b5_2
  - sqlite==3.30.1=hcee41ef_0
  - libffi==3.2.1=he1b5a44_1007
  - kiwisolver==1.2.0=py37h99015e2_0
  - libstdcxx-ng==9.2.0=hdf63c60_2
  - pcre==8.44=he1b5a44_0
  - markupsafe==1.1.1=py37h8f50634_1
  - libllvm9==9.0.1=hc9558a2_0
  - _libgcc_mutex==0.1=conda_forge
  - numpy==1.18.1=py37h8960a57_1
  - ipykernel==5.2.0=py37h43977f1_1
  - statsmodels==0.11.1=py37h8f50634_1
  - cairo==1.16.0=hcf35c78_1003
  - gettext==0.19.8.1=hc5be6a0_1002
  - python==3.7.6=h8356626_5_cpython
  - xorg-libxext==1.3.4=h516909a_0
  - boost==1.72.0=py37h9de70de_0
  - libsodium==1.0.17=h516909a_0
  - tornado==6.0.4=py37h8f50634_1
  - libgfortran-ng==7.3.0=hdf63c60_5
  - zeromq==4.3.2=he1b5a44_2
  - pandas==1.0.3=py37h0da4684_0
  - xorg-kbproto==1.0.7=h14c3975_1002
  - xorg-xproto==7.0.31=h14c3975_1007
  - libtiff==4.1.0=hc7e4089_6
  - libpng==1.6.37=hed695b0_1
  - xorg-libxdmcp==1.1.3=h516909a_0
  - pycairo==1.19.1=py37h01af8b0_3
  - libgcc-ng==9.2.0=h24d8f2e_2
  - glib==2.58.3=py37he00f558_1003
  - gst-plugins-base==1.14.5=h0935bb2_2
  - ....

I also tried listing the above packages under -pip: in the .yml file but I am still getting the error.

Thanks.

**Comment by patronov** [comment]
We updated the environment.yml to remove the build version. It should, hopefully work now.
Also, please note that we are just releasing REINVENT 3.0 so this tutorial will be also migrated to work with 3.0
Make sure to check out the correct branches for both REINVENT and Reinvent Community tutorials.

**Comment by MiloszGrabski** [comment]
Hi,
Issue still persists
...ReinventCommunity>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libxkbcommon=0.10.0
  - dbus=1.13.6
  - nss=3.47
  - nspr=4.25
  - readline=8.0
  - ld_impl_linux-64=2.34
  - ncurses=6.1
  - _openmp_mutex=4.5
  - gst-plugins-base=1.14.5
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libstdcxx-ng=9.2.0
  - gstreamer=1.14.5
  - libuuid=2.32.1

Thanks

**Comment by patronov** [comment]
Is this under Windows or Linux?

**Comment by MiloszGrabski** [comment]
Hi,
This is under windows
Cheers

**Comment by Shiska07** [comment]
@MiloszGrabski I was previously trying to run it on windows and issue still persisted but I switched to Linux and it's working fine so far.

**Comment by patronov** [comment]
Most of the repositories under MolecularAI are developed for Linux and havent been tested for Windows. Even if you set the environment to run under Windows there is a chance that something else within the code may misbehave. The simplest solution would be to use Linux if possible.
