### ISSUE TITLE
How to run notebooks correctly

### ISSUE THREAD

**Issue by xuzhang5788** [MolecularAI/ReinventCommunity#9]
Thanks for your repo where I can learn how to use Reinvent.
First of all, which notebook should I try first in terms of learning Reinvent? Do you have any proper orders? Secondly, I don't understand what you mean these
""""1.5  Run REINVENT

Now it is time to execute REINVENT locally. Note, that depending on the number of epochs (steps) and the execution time of the scoring function components, this might take a while. As we have only specified a low number of epochs and all components should be fairly quick, this should not take too long in our case though.

The command-line execution looks like this:

# activate envionment
conda activate reinvent_shared.v2.1

# execute REINVENT
python <your_path>/input.py <config>.json""""

Do you mean that I run REINVENT at the terminal instead of in the notebook? If that is the case, why did you have the !python **** cell after. I think I can run it in the notebook.
I tried Complete_Use-Case-DRD2_Demo.ipynb, everything was going well until I started to run REINVENT.
I got error messages as followings:
Traceback (most recent call last):
  File "../../Reinvent/input.py", line 6, in <module>
    from running_modes.manager import Manager
  File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 4, in <module>
    from running_modes.configurations import GeneralConfigurationEnvelope
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/__init__.py", line 2, in <module>
    from running_modes.configurations.scoring import ScoringRunnerComponents, ScoringRunnerConfiguration
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/__init__.py", line 1, in <module>
    from running_modes.configurations.scoring.scoring_runner_components import ScoringRunnerComponents
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/scoring_runner_components.py", line 3, in <module>
    from reinvent_scoring.scoring import ScoringFuncionParameters
ModuleNotFoundError: No module named 'reinvent_scoring'

I ran it at the terminal reinvent.v3.0 conda env, I got different errors like these:
Traceback (most recent call last):
  File "../../Reinvent/input.py", line 6, in <module>
    from running_modes.manager import Manager
  File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 4, in <module>
    from running_modes.configurations import GeneralConfigurationEnvelope
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/__init__.py", line 2, in <module>
    from running_modes.configurations.scoring import ScoringRunnerComponents, ScoringRunnerConfiguration
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/__init__.py", line 1, in <module>
    from running_modes.configurations.scoring.scoring_runner_components import ScoringRunnerComponents
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/scoring_runner_components.py", line 3, in <module>
    from reinvent_scoring.scoring import ScoringFuncionParameters
ModuleNotFoundError: No module named 'reinvent_scoring'

I am looking forward to getting your help. Many thanks

**Comment by patronov** [comment]
Hi, thanks for your interest in using our repo.

You can either run REINVENT from terminal or from the notebook. The notebook is simply to get you onboard and if you follow it through it should be possible to execute all the steps of the tutorials only through the notebook.
We have recently updated to REINVENT v.3.0 and the `reinvent_shared.v2.1` is relevant for the previous version. 
The correct environment name is 'reinvent.v3.0'.
Please, make sure you have got the latest state of the main branch and that you are using the `reinvent.v3.0` environment.
Do let us know if you still encounter issues as there is a chance we may have left some pointers to the old state of the code.

**Comment by xuzhang5788** [comment]
Thank you so much for your reply.

First of all, I pasted the wrong error messages when I ran it at the terminal. The right error messages are:
(reinvent.v3.0) xzhang@R1124G1:~/projects/Reinvent$ python input.py REINVENT_Use-Case-DRD2_demo/DRD2_config.json
Traceback (most recent call last):
  File "input.py", line 20, in <module>
    manager = Manager(configuration)
  File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 13, in __init__
    self._load_environmental_variables()
  File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 22, in _load_environmental_variables
    with open(os.path.join(project_root, '../configs/config.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhang/projects/Reinvent/running_modes/../configs/config.json'

Secondly, I have made some changes to cell 1
reinvent_dir = os.path.expanduser("/home/xzhang/projects/Reinvent")
reinvent_env = os.path.expanduser("~/miniconda3/envs/reinvent.v3.0")
output_dir = os.path.expanduser("/home/xzhang/projects/Reinvent/REINVENT_Use-Case-DRD2_demo")
and cell 8
configuration = {
  "version": 3,
  "run_type": "reinforcement_learning",
  "parameters": {
    "scoring_function": scoring_function
  }
}

**Comment by patronov** [comment]
Apologies for the slow response rate. 
Could you please check which version of reinvent-scoring library you have in your environment?
It should be the same as in the [reinvent.yml](https://github.com/MolecularAI/Reinvent/blob/master/reinvent.yml) file.

**Comment by xuzhang5788** [comment]
My reinvent.yml is like this:
name: reinvent.v3.0
channels:
  - rdkit
  - pytorch
  - openeye
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - _tflow_select=2.3.0
  - aiohttp=3.6.2
  - argon2-cffi=20.1.0
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.4.13
  - cachetools=4.2.2
  - cairo=1.14.12
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - click=8.0.0
  - cmarkgfm=0.4.2
  - colorama=0.4.4
  - coverage=5.5
  - cryptography=3.2.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cython=0.29.23
  - dacite=1.5.1
  - dataclasses=0.7
  - dbus=1.13.12
  - decorator=5.0.7
  - defusedxml=0.7.1
  - dill=0.3.1.1
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - google-auth=1.28.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jeepney=0.6.0
  - jinja2=2.11.3
  - joblib=0.15.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keras-preprocessing=1.1.2
  - keyring=21.5.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - multidict=4.7.3
  - multiprocess=0.70.9
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.9.0
  - notebook=6.3.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openeye-toolkits=2020.2.2
  - openssl=1.1.1k
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pathos=0.2.5
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - pkginfo=1.6.1
  - pluggy=0.13.1
  - pox=0.2.7
  - ppft=1.6.6.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - ptyprocess=0.7.0
  - py=1.8.1
  - py-boost=1.67.0
  - py4j=0.10.7
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydantic=1.8.2
  - pygments=2.7.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2019.3
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - rdkit=2020.03.3.0
  - readline=8.0
  - readme_renderer=27.0
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.4.0
  - rsa=4.7.2
  - scikit-learn=0.21.3
  - scipy=1.4.1
  - secretstorage=3.2.0
  - send2trash=1.5.0
  - setuptools=46.1.1
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard-plugin-wit=1.6.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - tqdm=4.43.0
  - traitlets=5.0.5
  - twine=3.2.0
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.4
  - yarl=1.4.2
  - zeromq=4.3.4
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - future==0.18.2
    - gast==0.2.2
    - grpcio==1.27.2
    - keras-applications==1.0.8
    - markdown==3.2.1
    - opt-einsum==3.2.0
    - protobuf==3.11.3
    - reinvent-chemistry==0.0.38
    - reinvent-models==0.0.3
    - reinvent-scoring==0.0.41
    - tensorboard==1.15.0
    - tensorflow==1.15.2
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - werkzeug==1.0.0
    
I used this file to create my reinvent.v3.0. Then I used conda list to check the version
# packages in environment at /home/xzhang/miniconda3/envs/reinvent.v3.0:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
_pytorch_select           0.1                       cpu_0    anaconda
_tflow_select             2.3.0                       mkl    anaconda
absl-py                   0.9.0                    pypi_0    pypi
aiohttp                   3.6.2            py37h8f50634_1    conda-forge
argon2-cffi               20.1.0           py37h4abf009_2    conda-forge
astor                     0.8.1                    pypi_0    pypi
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
blas                      1.0                         mkl    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2021.4.13            h06a4308_1  
cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
cairo                     1.14.12              h8948797_3  
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.3           py37h00ebd2e_1    conda-forge
chardet                   3.0.4           py37he5f6b98_1008    conda-forge
click                     8.0.0            py37h89c1867_0    conda-forge
cmarkgfm                  0.4.2            py37h4abf009_4    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
coverage                  5.5              py37h27cfd23_2  
cryptography              3.2.1            py37hc72a4ac_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1    anaconda
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.23          py37h2531618_0  
dacite                    1.5.1              pyh9f0ad1d_0    conda-forge
dataclasses               0.7                pyhb2cacf7_7    conda-forge
dbus                      1.13.12              h746ee38_0  
decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.1.1          py37hc8dfbb8_1    conda-forge
docutils                  0.16             py37h89c1867_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.9.1             he983fc9_1006    conda-forge
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
glib                      2.63.1               h5a9c865_0    anaconda
google-auth               1.28.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.27.2                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.10.0          nompi_py37h1e651dc_105    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.10.0           py37h89c1867_0    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
intel-openmp              2020.0                      166    anaconda
ipykernel                 5.3.4            py37h888b3d9_1    conda-forge
ipython                   7.22.0           py37h085eea5_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.17.0                   py37_0    anaconda
jeepney                   0.6.0              pyhd8ed1ab_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9b                   habf39ab_1    anaconda
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py37h89c1867_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py37h89c1867_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyring                   21.5.0           py37h89c1867_0    conda-forge
kiwisolver                1.1.0            py37h99015e2_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0                    21_mkl    conda-forge
libboost                  1.67.0               h46d08c1_4    anaconda
libcblas                  3.8.0                    21_mkl    conda-forge
libedit                   3.1.20181209         hc058e9b_0    anaconda
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0                    21_mkl    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.14.0               h8c45485_0  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_0    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libuv                     1.40.0               hd18ef5c_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
lz4                       3.1.1            py37h96bc0eb_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markdown                  3.2.1                    pypi_0    pypi
markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
matplotlib                3.1.3                    py37_0    anaconda
matplotlib-base           3.1.3            py37hef1b27d_0    anaconda
mistune                   0.8.4           py37h4abf009_1002    conda-forge
mkl                       2020.0                      166    conda-forge
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
more-itertools            8.2.0                      py_1    conda-forge
multidict                 4.7.3            py37h516909a_0    conda-forge
multiprocess              0.70.9           py37h8f50634_1    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py37h89c1867_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
ninja                     1.9.0                hc9558a2_1    conda-forge
notebook                  6.3.0            py37h06a4308_0  
numpy                     1.18.1           py37h8960a57_1    conda-forge
numpy-base                1.18.1           py37hde5b4d6_1  
oauthlib                  3.1.0              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openeye-toolkits          2020.2.2                 py37_0    openeye
openssl                   1.1.1k               h27cfd23_0  
opt-einsum                3.2.0                    pypi_0    pypi
packaging                 20.3                       py_0    anaconda
pandas                    1.0.3            py37h0da4684_1    conda-forge
pandoc                    2.12                 h7f98852_0    conda-forge
pandocfilters             1.4.3            py37h06a4308_1  
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pathos                    0.2.5                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    7.0.0            py37hb39fc2d_0    anaconda
pip                       21.2.4                   pypi_0    pypi
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.6.1              pyh9f0ad1d_0    conda-forge
pluggy                    0.13.1           py37h89c1867_4    conda-forge
pox                       0.2.7                      py_0    conda-forge
ppft                      1.6.6.1          py37hc8dfbb8_1    conda-forge
prometheus_client         0.10.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.17             pyha770c72_0    conda-forge
prompt_toolkit            3.0.17               hd8ed1ab_0    conda-forge
protobuf                  3.11.3                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.8.1                      py_0    conda-forge
py-boost                  1.67.0           py37h04863e7_4    anaconda
py4j                      0.10.7                     py_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                      py_0    anaconda
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydantic                  1.8.2            py37h27cfd23_0  
pygments                  2.7.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pyrsistent                0.17.3           py37h4abf009_1    conda-forge
pysocks                   1.7.1            py37h89c1867_3    conda-forge
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
python                    3.7.7           hcf32534_0_cpython    anaconda
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyzmq                     20.0.0           py37h5a562af_1    conda-forge
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rdkit                     2020.03.3.0      py37hc20afe1_1    rdkit
readline                  8.0                  he28a2e2_2    conda-forge
readme_renderer           27.0               pyh9f0ad1d_0    conda-forge
reinvent-chemistry        0.0.38                   pypi_0    pypi
reinvent-models           0.0.3                    pypi_0    pypi
reinvent-scoring          0.0.41                   pypi_0    pypi
requests                  2.25.0             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
rfc3986                   1.4.0              pyh9f0ad1d_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
scikit-learn              0.21.3           py37hcdab131_0    conda-forge
scipy                     1.4.1            py37ha3d9a3c_3    conda-forge
secretstorage             3.2.0            py37h89c1867_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.1.1           py37hc8dfbb8_0    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.31.1               h62c20be_1    anaconda
tensorboard               1.15.0                   pypi_0    pypi
tensorboard-plugin-wit    1.6.0              pyh9f0ad1d_0    conda-forge
tensorflow                1.15.2                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.9.4            py37h89c1867_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.8             h84994c4_1000    conda-forge
torch                     1.9.0+cu111              pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
tornado                   6.0.4            py37h8f50634_2    conda-forge
tqdm                      4.43.0                     py_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
twine                     3.2.0            py37hc8dfbb8_1    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.0                    pypi_0    pypi
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1            py37h89c1867_4    conda-forge
wrapt                     1.12.1           py37h4abf009_2    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h516909a_1002    conda-forge
yarl                      1.4.2            py37h7b6447c_0    anaconda
zeromq                    4.3.4                h2531618_0  
zipp                      2.2.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.3.7             h0a35d5f_1001    conda-forge

I checked they are the same.

**Comment by patronov** [comment]
Could you please try upgrading to reinvent-scoring==0.0.42 and the verify whether the same error message occurs?

**Comment by xuzhang5788** [comment]
Sorry. The same error message occured.
In addition. In the notebook,
If I run cell 
%%capture captured_err_stream --no-stderr

# execute REINVENT from the command-line
!python {reinvent_dir}/input.py {configuration_JSON_path}
It didn't do anything and no errors.
If I add a new cell, like this 
!python ../../Reinvent/input.py ../../Reinvent/REINVENT_Use-Case-DRD2_demo/DRD2_config.json
it showed error messages, same as before even though I updated reinvent-scoring to 0.0.42

Traceback (most recent call last):
  File "../../Reinvent/input.py", line 6, in <module>
    from running_modes.manager import Manager
  File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 4, in <module>
    from running_modes.configurations import GeneralConfigurationEnvelope
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/__init__.py", line 2, in <module>
    from running_modes.configurations.scoring import ScoringRunnerComponents, ScoringRunnerConfiguration
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/__init__.py", line 1, in <module>
    from running_modes.configurations.scoring.scoring_runner_components import ScoringRunnerComponents
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/scoring_runner_components.py", line 3, in <module>
    from reinvent_scoring.scoring import ScoringFuncionParameters
ModuleNotFoundError: No module named 'reinvent_scoring'

**Comment by patronov** [comment]
> First of all, I pasted the wrong error messages when I ran it at the terminal. The right error messages are:
> (reinvent.v3.0) xzhang@R1124G1:~/projects/Reinvent$ python input.py REINVENT_Use-Case-DRD2_demo/DRD2_config.json
> Traceback (most recent call last):
> File "input.py", line 20, in
> manager = Manager(configuration)
> File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 13, in **init**
> self._load_environmental_variables()
> File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 22, in _load_environmental_variables
> with open(os.path.join(project_root, '../configs/config.json'), 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhang/projects/Reinvent/running_modes/../configs/config.json'

Now reading again this part of your previously reported issue I realized that you are missing the `config.json` which should be placed in the folder that corresponds to: `https://github.com/MolecularAI/Reinvent/tree/master/configs` 
Please, see that you have this file as explained in REINVENT`s readme - section "Tests".

**Comment by xuzhang5788** [comment]
@patronov Thank you for your reply.

I still got the same error messages even I upgraded to reinvent-scoring==0.0.42.

**Comment by patronov** [comment]
Im not sure for the exact cause of the issue especially since you have the library installed.
We are currently amidst some breaking changes and we are preparing updated tutorials and several new features.
Perhaps with the new release these issues will be resolved for you.
Sorry for your troubles.

**Comment by xuzhang5788** [comment]
@patronov 
Thank you for your reply. Please let me know when you have the new release.
